### ISSUE TITLE
hello there, i am using this gallery as library in my project. but there is no MainActivity in code. please  let me know what can i do now ?

### ISSUE THREAD

**Issue by AshishParmar1209** [vidit135g/Floral#1]

**Comment by jaiminpatel11** [comment]
> No description provided

your isssue is solve or not i also not found a mainActivity

**Comment by vidit135g** [comment]
Sorry for so much hassles, I noticed the upload didn't worked fine and so I will upload the activity file sooner or later, thanks for reporting. 🙂
