### ISSUE TITLE
success on Android 13 

### ISSUE THREAD

**Issue by jenswes** [vidit135g/Floral#24]
Hello
i got the code from the waiting pull request here:

git clone -b androidx https://github.com/leso-kn/Floral.git
(thank you leso-kn)

accidently i had installed:
Android Studio Electric Eel | 2022.1.1 Patch 2
Build #AI-221.6008.13.2211.9619390, built on February 17, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 amd64

i opend the source folder, build and signed the project and installed it
on my Pixel 7a / Android 13 where it runs without problems.

But the pixel is new and i have only 3 images, so maybe issues will arrive in future.
I'll report back.

Thanks for your project

wespe

**Comment by vidit135g** [comment]
Hi Jenswes, thanks for your contribution to the repository. Let me know if the project is running on other pixel images as well. Thanks and happy coding.
