### ISSUE TITLE
MainActivity Not Found.

### ISSUE THREAD

**Issue by ghost** [vidit135g/Floral#3]
i am trying to edit your repository. but i can't find mainactivity in your code.

**Comment by aZyreTech** [comment]
getting same error

**Comment by V1sk** [comment]
Same here

**Comment by ForceGT** [comment]
There is a specific commit which says "Delete Main Activity" so probably this is intentional

**Comment by vidit135g** [comment]
Sorry for the inconvenience caused to you guys. I have uploaded the MainActivity. And bruh, this wasn't intentional for sure.
