### ISSUE TITLE
App crashing every time after "Get Started"

### ISSUE THREAD

**Issue by mizzunet** [vidit135g/Floral#4]
Version 1.0 downloaded from F-Droid

Steps:
1. Install app
2. Open it
3. Wait for "Get Started" button show up and tap on it
4. Showing loading till it crashes

Logs: http://transfer.sh/K1EdA/logs-2021-03-24-09-54-24.zip
Screen recording: http://transfer.sh/N0WGN/screen-20210324-095419.mp4

**Comment by VesperLlama** [comment]
It crashes on my phone too. Here are the logs from my phone.
https://del.dog/thuniwymah

The Play Store version is working fine but the IzzyonDroid version is crashing.

**Comment by RezurrectBodg** [comment]
Happens here too: Honor COR-L29

**Comment by vidit135g** [comment]
Similar error reported signature error maybe. Looking more into the issue, give me some time and I'll revert back to you guys. Thanks for reporting though.

**Comment by mizzunet** [comment]
Thanks

> Similar error reported signature error maybe. Looking more into the issue, give me some time and I'll revert back to you guys. Thanks for reporting though.

**Comment by vidit135g** [comment]
I have uploaded another version of the project in another repo named Floral_Gallery.

Changelog & fixes:

Force close error on Splash screen.
App crash when copying or moving the images.
Target SDK Version changed to 30.
Minor bug fixes.

here's the link to the new repository:

https://github.com/vidit135g/Floral_Gallery

**Comment by mizzunet** [comment]
> I have uploaded another version of the project in another repo named Floral_Gallery.
> 
> Changelog & fixes:
> 
> Force close error on Splash screen.
> App crash when copying or moving the images.
> Target SDK Version changed to 30.
> Minor bug fixes.
> 
> here's the link to the new repository:
> 
> https://github.com/vidit135g/Floral_Gallery

May I know where to get APK of this version?

**Comment by vidit135g** [comment]
Bro, in the release folder of the project itself!

**Comment by mizzunet** [comment]
> Bro, in the release folder of the project itself!

I can't seem to find under Releases and there isn'ta  Reslease folder in the project
![Screenshot_20210403-205748](https://user-images.githubusercontent.com/10193999/113483080-4c051d00-94bf-11eb-8d14-c003470ed100.png)

**Comment by mizzunet** [comment]
> Bro, in the release folder of the project itself!

Got it, thanks. Now it's working great, kudos

**Comment by vidit135g** [comment]
btw, there wasn't any major error, the crash while moving and copying was because of the theme of the material card view incompatible with the default app compat theme. Setting the card view theme within the layout fioe itself fixed the crash. Not very informative but just wanted to let you guys know about it.

Kudos ✌️

**Comment by mizzunet** [comment]
> btw, there wasn't any major error, the crash while moving and copying was because of the theme of the material card view incompatible with the default app compat theme. Setting the card view theme within the layout fioe itself fixed the crash. Not very informative but just wanted to let you guys know about it.
> 
> Kudos ✌️

I see, actuallly it didn't even let me in, it was just crashing. 
And I see you very talented especially in UI/UX design, all of your android app projects look stunning. Replify looks awesome than QKSMS, I love it. Sadly, that was crashing at opening as well

**Comment by vidit135g** [comment]
Thanks mate ✌️

**Comment by mizzunet** [comment]
Is it okay to ask if there would be any chance for updating Replify near future? I'm sorry if I'm being annoyance :D I really like it 😋

**Comment by vidit135g** [comment]
As of now I'm on a rehabilitation schedule from past 8 months due to a serious spine injury. Since then, therapies and surgeries are my only tasks. Will probably resume my work when I'm back to normal. 😏✌️

**Comment by vidit135g** [comment]
![Screenshot_20210407-101422.jpg](https://user-images.githubusercontent.com/20066231/113811855-9bcb3900-978a-11eb-913c-781fcac42fe4.jpg)
