### ISSUE TITLE
APK from F-Droid does not install.

### ISSUE THREAD

**Issue by coderkei** [vidit135g/Floral#6]
When installing this app from the IzzyOnDroid Repo on F-Droid, the APK fails to install on my device. Possibly the APK is corrupted?

Device is Oppo Reno running Android 10. Thanks.

![](https://i.ibb.co/t355Typ/Screenshot-2021-03-24-09-22-29-56.jpg)

**Comment by TaylanTatli** [comment]
Play Protect doesn't let me to install even i say force install.

**Comment by vidit135g** [comment]
Might be the signature error as the package wasn't uploaded directly via me on Fdroid. Looking into this. give me some time.

**Comment by coderkei** [comment]
@vidit135g IzzyOnDroid uses the APK from the releases section of your repo.

I have tried that APK and it gives the same error.

**Comment by vidit135g** [comment]
I have uploaded another version of the project in another repo named Floral_Gallery.

Changelog & fixes:

Force close error on Splash screen.
App crash when copying or moving the images.
Target SDK Version changed to 30.
Minor bug fixes.

**Comment by vidit135g** [comment]
I'll upload the app from my end, I guess someone else uploaded the apk file from my repo.

**Comment by emilio-millepiani** [comment]
Hi!
Which is the link for the repo and/or the file?
Thanks!

**Comment by vidit135g** [comment]
There you go:

https://github.com/vidit135g/Floral_Gallery

**Comment by vidit135g** [comment]
If you face any issues then let me know. In the meantime, I'm uploading my app on F-Droid. I'll let you know when it's done.

There you go:  

https://dev.to/sanandmv7/how-to-publish-your-apps-on-f-droid-2epn

I'm uploading the main apk file in this repo.

**Comment by emilio-millepiani** [comment]
I have installed the 'app-release.apk'. It's perfect!!!!

**Comment by vidit135g** [comment]
hehe, thanks ✌️

**Comment by coderkei** [comment]
@vidit135g Have you updated the build on the IzzyOnDroid repo for F-Droid? Its still listed as the 1.0 version that does not work.

Izzysoft isn't going to detect the fixed build if you uploaded it to a different repo, so it needs to be set to the new one. If you have already done this, I checked your Floral 2.0 repo and it has no releases currently.

https://android.izzysoft.de/repo/apk/com.absolute.floral

**Comment by vidit135g** [comment]
I'm updating my project as there were several issues related to scoped storage. I have to limit certain functionality of the app. I'll update you guys as soon as the project is updated.

As far as Fdroid is concerned, the app that is updated on it isn't uploaded by me. I'll upload a stable one and let you guys know.

**Comment by coderkei** [comment]
@vidit135g Thank you for your reply. No worries, I know how much of an issue scoped storage has been for app developers 😄
