### ISSUE TITLE
Can't delete pictures or videos

### ISSUE THREAD

**Issue by sonalder-darlene** [vidit135g/Floral#7]
Hello,
When I try to delete a picture or a video with the recycle bin logo it just says Done but the file is not deleted at all.
I tried to select it from the gallery (and not the picture itself) and doing Options(three dots) > Delete but it does exactly the same.
Please fix this

Device : Xiaomi Mi A2
Custom ROM : CalyxOS 2.2.0 (Android 11)

**Comment by vidit135g** [comment]
I'll surely check the problem and let you know when I fix it. Thanks for reporting though!
