### ISSUE TITLE
Crashes (unusable) when installed from github

### ISSUE THREAD

**Issue by sonalder-darlene** [vidit135g/Floral#8]
Hello,
I first downloaded Floral from a third-party f-droid repo and the app just kept crashing after I give it the stockage permission. So I went on the github to download the APK from there... same things happend.
Works fine with APK from Google PlayStore.

Device : Xiaomi Mi A2
Custom ROM : CalyxOS 2.2.0 (Android 11)

**Comment by vidit135g** [comment]
I have already explained that in another issue thread.
